Sprtint-7/homebanking/clientes/urls.py
from django.urls import path
from .views import IndexView, DetailView, nueva_tarjeta, eliminar_tarjeta, ayuda, nuevo_cliente

app_name = 'clientes'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', DetailView.as_view(), name='detalle'),
    path('<int:pk>/nueva-tarjeta/', nueva_tarjeta, name='nueva_tarjeta'),
    path('nuevo/', nuevo_cliente, name='nuevo_cliente'),
    path('tarjeta/<int:tarjeta_id>/eliminar/', eliminar_tarjeta, name='eliminar_tarjeta'),
    path('ayuda/', ayuda, name='ayuda'),
]

Sprtint-7/homebanking/homebanking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls', namespace='login')),
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('empleados/', include('empleados.urls', namespace='empleados')),
    path('prestamos/', include('prestamos.urls', namespace='prestamos')),
    path('tarjetas/', include('tarjetas.urls', namespace='tarjetas')),
]

Sprtint-7/homebanking/login/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view, help_view

app_name = 'login'

urlpatterns = [
    path('', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('help/', help_view, name='help'),
]

Sprtint-7/homebanking/prestamos/urls.py
from django.urls import path
from . import views

app_name = 'prestamos'

urlpatterns = [
    path('<int:cliente_id>/', views.lista_prestamos, name='lista_prestamos'),
    path('crear/<int:cliente_id>/', views.crear_prestamo, name='crear_prestamo'),
    path('<int:prestamo_id>/', views.detalle_prestamo, name='detalle_prestamo'),
    path('<int:prestamo_id>/pagar/', views.pagar_prestamo, name='pagar_prestamo'),
]

Sprtint-7/homebanking/prestamos/models.py
from django.db import models
from clientes.models import Cliente

class TipoPrestamo(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Prestamo(models.Model):
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    tipo = models.ForeignKey(TipoPrestamo, on_delete=models.CASCADE)
    fecha = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.valor} - {self.tipo} - {self.fecha} - {self.cliente}"

Sprtint-7/homebanking/prestamos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Prestamo, TipoPrestamo
from clientes.models import Cliente

def lista_prestamos(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    prestamos = Prestamo.objects.filter(cliente=cliente)
    return render(request, 'prestamos/lista_prestamos.html', {'prestamos': prestamos, 'cliente': cliente})

def detalle_prestamo(request, prestamo_id):
    prestamo = get_object_or_404(Prestamo, pk=prestamo_id)
    return render(request, 'prestamos/detalle_prestamo.html', {'prestamo': prestamo})

def crear_prestamo(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == 'POST':
        tipo_prestamo_id = request.POST['tipo_cliente']
        tipo_prestamo = TipoPrestamo.objects.get(id=tipo_prestamo_id)
        valor_solicitado = float(request.POST['valor'])

        
        prestamos_actuales = Prestamo.objects.filter(cliente=cliente)
        total_prestamos = sum(float(prestamo.valor) for prestamo in prestamos_actuales)
        
        
        if total_prestamos + valor_solicitado <= float(cliente.limite_prestamo):
            valor = valor_solicitado
        else:
            return HttpResponse(
                f"El monto solicitado excede el límite permitido. "
                f"Límite total: ${cliente.limite_prestamo}, "
                f"Préstamos actuales: ${total_prestamos}, "
                f"Disponible: ${float(cliente.limite_prestamo) - total_prestamos}"
            )

        nuevo_prestamo = Prestamo(
            valor=valor,
            tipo=tipo_prestamo,
            fecha=request.POST['fecha'],
            cliente=cliente
        )
        nuevo_prestamo.save()
        return redirect('prestamos:lista_prestamos', cliente_id=cliente.id)

    tipos_prestamo = TipoPrestamo.objects.all()
    prestamos_actuales = Prestamo.objects.filter(cliente=cliente)
    total_prestamos = sum(float(prestamo.valor) for prestamo in prestamos_actuales)
    disponible = float(cliente.limite_prestamo) - total_prestamos

    return render(request, 'prestamos/crear_prestamo.html', {
        'cliente': cliente, 
        'tipos_prestamo': tipos_prestamo,
        'limite_prestamo': cliente.limite_prestamo,
        'total_prestamos': total_prestamos,
        'disponible': disponible
    })

def pagar_prestamo(request, prestamo_id):
    prestamo = get_object_or_404(Prestamo, pk=prestamo_id)
    if request.method == 'POST':
        cliente_id = prestamo.cliente.id
        prestamo.delete()
        return redirect('prestamos:lista_prestamos', cliente_id=cliente_id)
    return render(request, 'prestamos/pagar_prestamo.html', {'prestamo': prestamo})

Sprtint-7/homebanking/prestamos/templates/prestamos/crear_prestamo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Crear Préstamo</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'prestamos/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Crear Nuevo Préstamo</h1>
        <form method="post">
            {% csrf_token %}
            <div>
                <label for="cliente">Cliente:</label>
                <p><strong>{{ cliente.nombre }} </strong></p>
                <input type="hidden" name="cliente" value="{{ cliente.id }}">
            </div>

            <div>
                <label for="tipo_cliente">Tipo de Préstamo:</label>
                <select name="tipo_cliente" id="tipo_cliente">
                    {% for tipo in tipos_prestamo %}
                        <option value="{{ tipo.id }}">{{ tipo }}</option>
                    {% endfor %}
                </select>
            </div>

            <div>
                <label for="fecha">Fecha:</label>
                <input type="date" name="fecha" id="fecha" required>
            </div>

            <div>
                <label for="valor">Valor del Préstamo:</label>
                <input type="number" name="valor" id="valor" required max="{{ disponible }}" step="0.01">
                <div class="limites-info">
                    <small>Límite máximo total: ${{ limite_prestamo }}</small>
                    <small>Préstamos actuales: ${{ total_prestamos }}</small>
                    <small>Disponible para préstamos: ${{ disponible }}</small>
                </div>
            </div>

            <button type="submit">Guardar</button>
        </form>
        <a href="{% url 'clientes:index' %}" class="back-button">Volver a la Lista</a>
    </div>
</body>
</html>

Sprtint-7/homebanking/prestamos/templates/prestamos/detalle_prestamo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Detalle del Préstamo</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'prestamos/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Detalle del Préstamo</h1>
        <p>Valor: {{ prestamo.valor }}</p>
        <p>Tipo: {{ prestamo.tipo }}</p>
        <p>Fecha: {{ prestamo.fecha }}</p>
        <p>Cliente: {{ prestamo.cliente }}</p>
        <form method="post" action="{% url 'prestamos:pagar_prestamo' prestamo.id %}">
            {% csrf_token %}
            <button type="submit">Pagar</button>
        </form>
        <a class="back-button" href="{% url 'prestamos:lista_prestamos' %}">Volver a la lista de préstamos</a>
    </div>
</body>
</html>

Sprtint-7/homebanking/prestamos/templates/prestamos/lista_prestamos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Préstamos</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'prestamos/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Lista de Préstamos de {{ cliente.nombre }} {{ cliente.apellido }}</h1>
        <ul>
            {% for prestamo in prestamos %}
                <li><a href="{% url 'prestamos:detalle_prestamo' prestamo.id %}">{{ prestamo }}</a></li>
            {% endfor %}
        </ul>
        <div class="button-container">
            <p><a class="back-button" href="{% url 'clientes:detalle' cliente.id %}">Volver a detalles del cliente</a>
            <a class="button" href="{% url 'prestamos:crear_prestamo' cliente.id %}">Agregar préstamo</a>
        </div>
    </div>
</body>
</html>

Sprtint-7/homebanking/prestamos/templates/prestamos/pagar_prestamo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Pagar Préstamo</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'prestamos/styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Pagar Préstamo</h1>
        <p>¿Estás seguro de que deseas saldar el préstamo de {{ prestamo.valor }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Pagar</button>
        </form>
        <p><a class="back-button" href="{% url 'prestamos:lista_prestamos' %}">Volver a la lista de préstamos</a></p>
    </div>
</body>
</html>