Sprtint-7/homebanking/clientes/urls.py
from django.urls import path
from .views import IndexView, DetailView, nueva_tarjeta, eliminar_tarjeta, ayuda, nuevo_cliente

app_name = 'clientes'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', DetailView.as_view(), name='detalle'),
    path('<int:pk>/nueva-tarjeta/', nueva_tarjeta, name='nueva_tarjeta'),
    path('nuevo/', nuevo_cliente, name='nuevo_cliente'),
    path('tarjeta/<int:tarjeta_id>/eliminar/', eliminar_tarjeta, name='eliminar_tarjeta'),
    path('ayuda/', ayuda, name='ayuda'),
]

Sprtint-7/homebanking/empleados/urls.py
from django.urls import path
from .views import EmpleadoListView, EmpleadoCreateView, EmpleadoUpdateView, EmpleadoDetailView, EmpleadoDeleteView

app_name = 'empleados'

urlpatterns = [
    path('', EmpleadoListView.as_view(), name='lista_empleados'),
    path('crear/', EmpleadoCreateView.as_view(), name='crear_empleado'),
    path('editar/<int:pk>/', EmpleadoUpdateView.as_view(), name='editar_empleado'),
    path('detalle/<int:pk>/', EmpleadoDetailView.as_view(), name='detalle_empleado'),
    path('eliminar/<int:pk>/', EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

Sprtint-7/homebanking/homebanking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls', namespace='login')),
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls', namespace='clientes')),
    path('empleados/', include('empleados.urls', namespace='empleados')),
    path('prestamos/', include('prestamos.urls', namespace='prestamos')),
    path('tarjetas/', include('tarjetas.urls', namespace='tarjetas')),
]

Sprtint-7/homebanking/login/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view, help_view

app_name = 'login'

urlpatterns = [
    path('', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('help/', help_view, name='help'),
]

Sprtint-7/homebanking/empleados/models.py
from django.db import models
from clientes.models import Sucursal

class Empleado(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    dni = models.CharField(max_length=10, unique=True)
    fecha_contratacion = models.DateField()
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"

Sprtint-7/homebanking/empleados/forms.py
# forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['nombre', 'apellido', 'dni', 'fecha_contratacion', 'sucursal']

Sprtint-7/homebanking/empleados/views.py
# views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Empleado
from .forms import EmpleadoForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Vista para listar empleados
@method_decorator(login_required, name='dispatch')
class EmpleadoListView(ListView):
    model = Empleado
    context_object_name = 'empleados'


@method_decorator(login_required, name='dispatch')
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'empleados/detalle_empleado.html'


@method_decorator(login_required, name='dispatch')
class EmpleadoCreateView(CreateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name = 'empleados/crear_empleado.html'
    success_url = reverse_lazy('empleados:lista_empleados')


@method_decorator(login_required, name='dispatch')
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name = 'empleados/editar_empleado.html'
    success_url = reverse_lazy('empleados:lista_empleados')


@method_decorator(login_required, name='dispatch')
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'empleados/eliminar_empleado.html'
    success_url = reverse_lazy('empleados:lista_empleados')

Sprtint-7/homebanking/empleados/templates/empleados/crear_empleado.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Crear Empleado</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'empleados/styles.css' %}">
  </head>
  <body>
    <div class="container">
      <h1>Crear Nuevo Empleado</h1>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Guardar</button>
      </form>
      <p><a class="back-button" href="{% url 'empleados:lista_empleados' %}">Volver a la lista de empleados</a></p>
    </div>
  </body>
</html>

Sprtint-7/homebanking/empleados/templates/empleados/detalle_empleado.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Detalle de Empleado</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'empleados/styles.css' %}">
  </head>
  <body>
    <div class="client-details">
      <h1>Detalle del Empleado</h1>
      <p><strong>Nombre:</strong> {{ empleado.nombre }}</p>
      <p><strong>Apellido:</strong> {{ empleado.apellido }}</p>
      <p><strong>DNI:</strong> {{ empleado.dni }}</p>
      <p><strong>Fecha de Contratación:</strong> {{ empleado.fecha_contratacion }}</p>
      <p><a class="goback" href="{% url 'empleados:lista_empleados' %}">Volver a la lista de empleados</a></p>
    </div>
  </body>
</html>

Sprtint-7/homebanking/empleados/templates/empleados/editar_empleado.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Editar Empleado</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'empleados/styles.css' %}">
  </head>
  <body>
    <div class="container">
      <h1>Editar Empleado</h1>
      <h1>Editar al empleado "{{ empleado.nombre }} {{ empleado.apellido }}"</h1>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button class="button" type="submit">Actualizar</button>
      </form>
    </div>
    <p><a class="goback" href="{% url 'empleados:lista_empleados' %}">Volver a la lista de empleados</a></p>
  </body>
</html>

Sprtint-7/homebanking/empleados/templates/empleados/eliminar_empleado.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Eliminar Empleado</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'empleados/styles.css' %}">
  </head>
  <body>
    <div class="container">
      <h1>Eliminar Empleado</h1>
      <h1>¿Estás seguro de que deseas eliminar al empleado "{{ empleado.nombre }} {{ empleado.apellido }}"?</h1>
      <form method="post">
        {% csrf_token %}
        <button class="delete-button-custom" type="submit">Eliminar</button>
      </form>
      <p><a class="button" href="{% url 'empleados:lista_empleados' %}">Volver a la lista de empleados</a></p>
    </div>
  </body>
</html>

Sprtint-7/homebanking/empleados/templates/empleados/empleado_list.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Lista de Empleados</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'empleados/styles.css' %}">
  </head>
  <body>
    <h1>Lista de Empleados</h1>
    <table border="1">
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>DNI</th>
        <th>Fecha de Contratación</th>
        <th>Acciones</th>
      </tr>
      {% for empleado in empleados %}
      <tr>
        <td>{{ empleado.id }}</td>
        <td>{{ empleado.nombre }}</td>
        <td>{{ empleado.apellido }}</td>
        <td>{{ empleado.dni }}</td>
        <td>{{ empleado.fecha_contratacion }}</td>
        <td>
          <a href="{% url 'empleados:detalle_empleado' empleado.id %}">Ver Detalle</a> |
          <a href="{% url 'empleados:editar_empleado' empleado.id %}">Editar</a> |
          <a href="{% url 'empleados:eliminar_empleado' empleado.id %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
    </table>
    <a class="button" href="{% url 'empleados:crear_empleado' %}">Agregar Nuevo Empleado</a>
    <a class="switch-button" href="{% url 'clientes:index' %}">Ir a menú clientes</a>
    <a class="logoutbutton" href="{% url 'login:logout' %}">Cerrar sesión</a>
  </body>
</html>